branch-defaults:
  main:
    environment: path-lab-report-dev2
    group_suffix: null
environment-defaults:
  path-lab-report-dev2:
    branch: null
    repository: null
global:
  application_name: path-lab-report
  default_ec2_keyname: my_first_key
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
