# Generated by Django 4.0.5 on 2022-06-15 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_exam', models.TextField(verbose_name='gross examination')),
                ('microscopic_exam', models.TextField(verbose_name='microscopic examination')),
                ('immuno_examination', models.TextField(verbose_name='immunohistochemistry examination')),
                ('special_stain_exam', models.TextField(verbose_name='special stain examination')),
                ('diagnosis', models.TextField()),
                ('medical_codes', models.TextField()),
                ('topography_codes', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='report')),
            ],
        ),
    ]
