# Generated by Django 4.0.5 on 2022-06-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_alter_patient_options_alter_account_managers_and_more'),
        ('report', '0003_alter_report_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='account',
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_report', to=settings.AUTH_USER_MODEL, verbose_name='doctor_report'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_report', to='account.patient', verbose_name='patient_report'),
        ),
    ]
