# Generated by Django 4.0.5 on 2022-06-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='PatientViewSet',
        ),
    ]
