# Generated by Django 4.0.5 on 2022-06-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient'},
        ),
    ]
